@startuml
title Add New Printer System Sequence Diagram
Actor User
User -> MainActivity : onCreate
User -> MainActivity : onOptionsItemSelected
User -> MainActivity : enter ip
User -> MainActivity : submit
Actor SNMP
MainActivity -> SNMP : requests ip
MainActivity <-- SNMP : returns ip
@enduml