@startuml
title Class Diagram

class Activity
class ActionBarActivity
class SplashScreen
class MainActivity
class PrinterController
class snmpServer
class Printer
class dbHandler
class SQLiteOpenHelper
class LevelAdapter

Activity <|- ActionBarActivity
MainActivity --|> ActionBarActivity
SplashScreen ---|> Activity
PrinterController ---|> Activity
snmpServer ---|> Activity
dbHandler --|> SQLiteOpenHelper
LevelAdapter --|> ArrayAdapter

SplashScreen : #onCreate(savedInstanceState : Bundle) : void

MainActivity : -Button submit
MainActivity : -TextView outputText
MainActivity : -snmpServer prntStat
MainActivity : -AsyncTask theTask
MainActivity : #onCreate(savedInstanceState : Bundle) : void
MainActivity : +onCreateOptionsMenu(menu : Menu) : boolean
MainActivity : +onOptionsItemSelected(item : MenuItem) : boolean
MainActivity : #onActivityResult(requestCode : int, resultCode : int, data : Intent) : void
MainActivity : -showUserSettings() : void

PrinterController : #onCreate(savedInstanceState : Bundle) : void
PrinterController : #onPause() : void

snmpServer : -outText : TextView
snmpServer : +snmpGet(strIPAddress : String, community : String, iSNMPVersion : int, strOID : String) : String

Printer : -ipAddr : String
Printer : -name : String

dbHandler : + dbHandler(context : context) : dbHandler
dbHandler : + onCreate(db : SQLiteDatabase) : void
dbHandler : + onUpgrade(db : SQLiteDatabase, oldVersion : int, newVersion : int) : void
dbHandler : + addContact(p : Printer) : void
dbHandler : + getPrinter(id : int) : Printer
dbHandler : + getAllPrinters() : List<Printer>
dbHandler : + updatePrinter(p : Printer) : int
dbHandler : + deletePrinter(p : Printer) : void
dbHandler : + deletePrinterID(id : long) : void

MainActivity "1" -- "1" PrinterController : launches >
MainActivity "1" - "1" snmpServer : calls >

PrinterController "1" -- "1" Printer : adds >
PrinterController"1" *--- "1"dbHandler : contains >
PrinterController"1" *- "1"LevelAdapter : contains >

@enduml