@startuml
title Class Diagram

class Activity
class ActionBarActivity
class SplashScreen
class MainActivity
class PrinterController
class snmpServer
class Printer

Activity <|-- ActionBarActivity
MainActivity --|> ActionBarActivity
SplashScreen ---|> Activity
PrinterController ---|> Activity
snmpServer ---|> Activity

SplashScreen : #onCreate(savedInstanceState : Bundle) : void

MainActivity : -Button submit
MainActivity : -TextView outputText
MainActivity : -snmpServer prntStat
MainActivity : -AsyncTask theTask
MainActivity : #onCreate(savedInstanceState : Bundle) : void
MainActivity : +onCreateOptionsMenu(menu : Menu) : boolean
MainActivity : +onOptionsItemSelected(item : MenuItem) : boolean
MainActivity : #onActivityResult(requestCode : int, resultCode : int, data : Intent) : void
MainActivity : -showUserSettings() : void

PrinterController : #onCreate(savedInstanceState : Bundle) : void
PrinterController : #onPause() : void

snmpServer : -outText : TextView
snmpServer : +snmpGet(strIPAddress : String, community : String, iSNMPVersion : int, strOID : String) : String

Printer : -ipAddr : String
Printer : -name : String

MainActivity "1" -- "1" PrinterController : launches >
MainActivity "1" - "1" snmpServer : calls >

PrinterController "1" -- "1" Printer : adds >

@enduml