@startuml
title Snake SSD
actor snakeCharmer
participant HISSS
participant App

snakeCharmer -> App: start
par while !end of game
note right:  UC: Charm Snake
snakeCharmer <-- App: SnakePit
note right: UC: View SnakePit
snakeCharmer <-- App: App
snakeCharmer <-- App: Apple
else

opt charm
snakeCharmer -> App: direction
note right: UC: Beguile Snake
end
end
snakeCharmer <-- App: Score
note right: UC: View Count of Eaten Apples
App -> HISSS: transmitScore
note right: UC: Publish Count of Eaten Apples
@enduml