@startuml
title snmpServer_getPrintStatus
-> snmpServer : getPrintStatus(strIPAddress : String, community : String, iSNMPVersion : int, strOID : String) : int
alt try
snmpServer -> InetAddress : getByName(strIPAddress)
snmpServer -> SNMPv1CommunicationInterface : comInterface = new SNMPv1CommunicationInterface(iSNMPVersion, hostAddress, community)
snmpServer -> SNMPv1CommunicationInterface : comInterface.getMIBEntry(strOID)
snmpServer -> SNMPVarBindList : newVars.getSNMPObjectAt(0)
snmpServer -> SNMPSequence : pair.getSNMPObjectAt(1)
snmpServer -> Integer : Integer.valueOf(snmpValue)
else catch Exception e
snmpServer -> System : System.out.println(e)
end
<- snmpServer : return str : int
@enduml